-- ============================================================
-- TEAM SPACE V2 — SUPABASE SETUP
-- Re-runnable / idempotent
-- ============================================================

create extension if not exists pgcrypto;

-- ---------- TABLES ----------
create table if not exists public.team_members (
  slug text primary key,
  display_name text not null unique,
  color text not null default '#B0D9FA',
  auth_user_id uuid unique references auth.users(id) on delete set null,
  is_owner boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.team_projects (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  project_type text not null default 'COVER',
  song_formation text not null default 'TEAM',
  deadline timestamptz not null,
  priority text not null default 'normal',
  member_slugs text[] not null default '{}',
  links jsonb not null default '{}'::jsonb,
  tasks jsonb not null default '[]'::jsonb,
  notes text not null default '',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint team_projects_priority_check
    check (priority in ('low','normal','high','urgent')),
  constraint team_projects_formation_check
    check (song_formation in ('SOLO','DUO','TRIPLE','TEAM','GROUP'))
);

create table if not exists public.team_project_tests (
  id uuid primary key default gen_random_uuid(),
  candidate_name text not null,
  deadline date not null,
  reviewer_slugs text[] not null default '{}',
  bandlab_url text not null default '',
  original_url text not null default '',
  test_tasks jsonb not null default '[]'::jsonb,
  notes text not null default '',
  status text not null default 'testing',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint team_project_tests_status_check
    check (status in ('testing','passed','not_passed'))
);

create table if not exists public.team_activity (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_member_slug text,
  action_text text not null,
  created_at timestamptz not null default now()
);

-- ---------- DEFAULT 8 MEMBERS ----------
insert into public.team_members (slug, display_name, color)
values
  ('shota',  'Shota',  '#B0D9FA'),
  ('vani',   'Vani',   '#66FFCC'),
  ('shoto',  'Shoto',  '#3A1865'),
  ('mikon',  'Mikon',  '#A481C2'),
  ('elis',   'Elis',   '#940912'),
  ('hikari', 'Hikari', '#E0115F'),
  ('ebi',    'Ebi',    '#97A2FF'),
  ('zanith', 'Zanith', '#66C1FF')
on conflict (slug) do update
set display_name = excluded.display_name,
    color = excluded.color;

-- ---------- UPDATED_AT ----------
create or replace function public.team_set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_team_projects_updated_at on public.team_projects;
create trigger trg_team_projects_updated_at
before update on public.team_projects
for each row execute function public.team_set_updated_at();

drop trigger if exists trg_team_project_tests_updated_at on public.team_project_tests;
create trigger trg_team_project_tests_updated_at
before update on public.team_project_tests
for each row execute function public.team_set_updated_at();

-- ---------- SECURITY HELPERS ----------
create or replace function public.is_team_member()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.team_members
    where auth_user_id = auth.uid()
      and is_active = true
  );
$$;

create or replace function public.is_team_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.team_members
    where auth_user_id = auth.uid()
      and is_active = true
      and is_owner = true
  );
$$;

revoke all on function public.is_team_member() from public;
revoke all on function public.is_team_owner() from public;
grant execute on function public.is_team_member() to authenticated;
grant execute on function public.is_team_owner() to authenticated;

-- ---------- RLS ----------
alter table public.team_members enable row level security;
alter table public.team_projects enable row level security;
alter table public.team_project_tests enable row level security;
alter table public.team_activity enable row level security;

drop policy if exists "members_read_workspace_roster" on public.team_members;
create policy "members_read_workspace_roster"
on public.team_members
for select
to authenticated
using (public.is_team_member());

-- Roster/account mapping is owner-only.
drop policy if exists "owner_insert_members" on public.team_members;
create policy "owner_insert_members"
on public.team_members
for insert
to authenticated
with check (public.is_team_owner());

drop policy if exists "owner_update_members" on public.team_members;
create policy "owner_update_members"
on public.team_members
for update
to authenticated
using (public.is_team_owner())
with check (public.is_team_owner());

drop policy if exists "owner_delete_members" on public.team_members;
create policy "owner_delete_members"
on public.team_members
for delete
to authenticated
using (public.is_team_owner());

-- All authenticated workspace members can fully collaborate on projects.
drop policy if exists "members_all_projects" on public.team_projects;
create policy "members_all_projects"
on public.team_projects
for all
to authenticated
using (public.is_team_member())
with check (public.is_team_member());

drop policy if exists "members_all_project_tests" on public.team_project_tests;
create policy "members_all_project_tests"
on public.team_project_tests
for all
to authenticated
using (public.is_team_member())
with check (public.is_team_member());

drop policy if exists "members_read_activity" on public.team_activity;
create policy "members_read_activity"
on public.team_activity
for select
to authenticated
using (public.is_team_member());

drop policy if exists "members_insert_activity" on public.team_activity;
create policy "members_insert_activity"
on public.team_activity
for insert
to authenticated
with check (
  public.is_team_member()
  and actor_user_id = auth.uid()
);

-- ---------- DATA API GRANTS ----------
revoke all on public.team_members from anon;
revoke all on public.team_projects from anon;
revoke all on public.team_project_tests from anon;
revoke all on public.team_activity from anon;

grant select on public.team_members to authenticated;
grant insert, select, update, delete on public.team_projects to authenticated;
grant insert, select, update, delete on public.team_project_tests to authenticated;
grant insert, select on public.team_activity to authenticated;
grant usage, select on sequence public.team_activity_id_seq to authenticated;

-- ---------- REALTIME (idempotent) ----------
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'team_projects'
  ) then
    alter publication supabase_realtime add table public.team_projects;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'team_project_tests'
  ) then
    alter publication supabase_realtime add table public.team_project_tests;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'team_activity'
  ) then
    alter publication supabase_realtime add table public.team_activity;
  end if;
end $$;

-- ============================================================
-- AFTER CREATING AUTH USERS IN:
-- Supabase Dashboard > Authentication > Users
--
-- Link each Auth user to the correct roster member.
-- Replace the example emails below with the real account emails.
-- ============================================================

-- Example:
-- update public.team_members tm
-- set auth_user_id = au.id
-- from auth.users au
-- where tm.slug = 'shota'
--   and lower(au.email) = lower('shota@example.com');

-- Repeat for:
-- shota, vani, shoto, mikon, elis, hikari, ebi, zanith

-- Mark the web holder / owner AFTER their auth_user_id is linked:
-- update public.team_members
-- set is_owner = true
-- where slug = 'shota';

-- ============================================================
-- OPTIONAL SAMPLE PROJECT
-- Run only if you want a test card:
--
-- insert into public.team_projects
-- (name, project_type, song_formation, deadline, priority, member_slugs, links, tasks, notes)
-- values (
--   'VIRTUAL TO LIVE Cover',
--   'COVER',
--   'TEAM',
--   now() + interval '7 days',
--   'high',
--   array['shota','vani','mikon','ebi'],
--   '{"original":"https://www.youtube.com/"}'::jsonb,
--   '[{"id":"task-1","title":"Chia line","assigneeId":"shota","done":false}]'::jsonb,
--   'Project mẫu'
-- );
-- ============================================================
